### ISSUE TITLE
Github pages 404

### ISSUE THREAD

**Issue by somejavadev** [vromero/activemq-artemis-helm#15]
Hi @vromero,
I am trying to install activemq-artemis via the helm chart but it seems your github pages (https://vromero.github.io) are returning a 404. Is there an alternative way to install the helm chart?

**Comment by vromero** [comment]
sorry there is a typo somewhere, try cloning and `helm install activemq-artemis`  from there. I'll leave issue open till I fix the instrucions.

**Comment by somejavadev** [comment]
No problem, thanks for the quick response.
