### ISSUE TITLE
LoadBalancer service pendiing

### ISSUE THREAD

**Issue by kratosmat** [vromero/activemq-artemis-helm#36]
Hi,
I am trying to install your artemis helm on a rancher cluster.
After installing the deployment the service remains in pending state.

Has someone experienced the same issue?

Thanks,
Matteo.

**Comment by vromero** [comment]
Hi Matteo, sadly this is normal. This is a work in progress and I haven't figured out yet the solution (perhaps qpid router?) as in artemis the slave will keep the ports closed this creates some problems, either load balancer sending requests to a slave, non set up node or a service working but not showing up as completed. 
I'll fix it eventually, but as I'm sure its clear, I keep this project as low priority.
