### ISSUE TITLE
Messages arriving on the wrong master never consumed?

### ISSUE THREAD

**Issue by micgn** [vromero/activemq-artemis-helm#40]
The part I do not understand regarding the provided setup is the following - which might be of course due to the fact I am new with Artemis:
I register my consumer at the service ...-activemq-artemis, which routes me to one of the 2 master brokers (k8s replicas). The same I do with my producer and there I might end up on the other master. As far as I see in the broker config there is not setting for redistributing of messages between the 2 masters. So I end up with messages which are never consumed, right?
One solution coming to my mind would be having the replicated masters redistributing or maybe registering consumers at master-0 as well as at master-1. But how to achieve this with 2 master brokers accessible only through one service?

**Comment by DanSalt** [comment]
Hi @micgn,

See the config line here:
https://github.com/vromero/activemq-artemis-helm/blob/master/activemq-artemis/templates/configmap.yaml#L40

This tells Artemis that if there are consumers connected on the other broker, to replicate messages to them.

From the Artemis [Documentation](https://activemq.apache.org/components/artemis/documentation/1.1.0/clusters.html):

> If this is set to ON_DEMAND then Apache ActiveMQ Artemis will only forward messages to other nodes of the cluster if the address to which they are being forwarded has queues which have consumers, and if those consumers have message filters (selectors) at least one of those selectors must match the message. Using ON_DEMAND is like setting the legacy forward-when-no-consumers parameter to false.

Hope this helps,

Cheers,
Dan

**Comment by micgn** [comment]
Thanks for the hint, but in my tests on the cloud the messages are also practically not consumed. Wondering what is wrong. Might be that I have a problem on the client side in the way I create my ActiveMQConnectionFactory. Any idea how I should connect?

**Comment by micgn** [comment]
Actually I find no way to get this working - producers and consumers end up on different brokers and no replication does happen.

**Comment by DanSalt** [comment]
Hi @micgn  -- out of interest, what are your queue/topics called? I notice that the current charts are using the configuration where they will only cluster destinations starting with "jms"
https://github.com/vromero/activemq-artemis-helm/blob/master/activemq-artemis/templates/configmap.yaml#L32

In our local deployment, we have that removed, so that all destinations are clustered.
e.g.
`<address></address>`

Maybe worth trying that and see if it helps you?

**Comment by micgn** [comment]
@DanSalt -- you are a hero and certainly get some beer for free when coming to Munich...

**Comment by DanSalt** [comment]
@micgn -- great to hear!! Wondering I should create a PR that sets that to empty by default. @vromero what do you think?

**Comment by micgn** [comment]
Well after loosing almost a day on this I would certainly vote for yes...

**Comment by vromero** [comment]
@DanSalt is a hero indeed. Thanks for keeping an eye on the project's issues.
I'm happy to merge such a change.
