### ISSUE TITLE
activemq-artemis ingress controller not works

### ISSUE THREAD

**Issue by mug3n451** [vromero/activemq-artemis-helm#54]
Hi @vromero ,
i'm trying to install your activemq-artemis-helm on a RKE cluster. All works fine but i couldn't deploy the principal service as LoadBalancer so i have tried to use a ingress controller but i have a problem.
When i do the login after few second i have been redirected to login page  again.
If i do a portforward of the svc all work fine.
Which could be the problem?
here my ingress:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-t82ds
    field.cattle.io/ingressState: '{"YXJ0ZW1pcy1hY3RpdmVtcS9kZWZhdWx0L2FydGVtaXMtbWFzdGVyLnNtYXJ0cm9hZC1jY2wtZGV2LmNvcnAvLy84MTYx":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["10.64.20.23","10.64.20.24","10.64.20.25","10.64.20.26","10.64.20.27"],"port":80,"protocol":"HTTP","serviceName":"default:activemq-activemq-artemis","ingressName":"default:artemis-activemq","hostname":"artemis-master.smartroad-ccl-dev.corp","path":"/","allNodes":false}]'
  creationTimestamp: "2020-11-04T11:07:05Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: networking.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: nginx-ingress-controller
    operation: Update
    time: "2020-11-04T11:07:57Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: rancher
    operation: Update
    time: "2020-11-04T11:07:57Z"
  name: artemis-activemq
  namespace: default
  resourceVersion: "3808148"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/artemis-activemq
  uid: 978535ba-7002-41ac-a5d1-87bdb96274fd
spec:
  rules:
  - host: artemis-master.smartroad-ccl-dev.corp
    http:
      paths:
      - backend:
          serviceName: activemq-activemq-artemis
          servicePort: 8161
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.64.20.23
    - ip: 10.64.20.24
    - ip: 10.64.20.25
    - ip: 10.64.20.26
    - ip: 10.64.20.27`

thanks for the support
Cristian

**Comment by erlisb** [comment]
Hi @vromero,
We have the same issue and we are planning to deploy activemq for production use.

Is there any update regarding this issue ?

Thank you,
eb

**Comment by vromero** [comment]
I'm afraid any kind of load balancing drives Artemis nuts. You are likely hitting two different instances. I was planning to meet with a few users in #50 hopefully getting a hold of @DanSalt (the only other common contributor) but failed to do so.

So I guess I'll follow my plan and remove all loadbalancing and do it the artemis way, which is exposing the master and slave specifically as two different hostnames which also implies I'll remove the replica factor as it doesn't make sense with artemis as both artemis and kubernetes are doing the exact same job of choosing where the master/slaves run, and frankly kubernetes does a better job.

**Comment by FrankMormino** [comment]
@vromero - I have just arrived upon this issue and was curious if you were able to make progress with you plan to remove all load balancing and do this the artemis way.
Thank you for all your work and effort - truly appreciated 👍

**Comment by rubelw** [comment]
Anyone have an example or solution for load balancing?  Much appreciated...Thanks!
